### ISSUE TITLE
Move emoji description to the subtitle and use lowercase

### ISSUE THREAD

**Issue by xilopaint** [jukben/alfred-emoji#1]
Thank you for sharing. The AI search is very convenient. The all caps description in the title is a bit irritating though. Could you move it to the subtitle and use lowercase?

**Comment by jukben** [comment]
Hi, thanks for the support, apriciated it. 

What do you think about this?
<img width="593" alt="screen shot 2017-10-05 at 21 44 19" src="https://user-images.githubusercontent.com/8135252/31249106-6672eb96-aa16-11e7-911c-2b58d435025d.png">

I'm kinda struggling with the title, it can't be omitted. What do you suggesting?

**Comment by jukben** [comment]
Or maybe this one? Maybe this looks more artsy than the current version. 🤓

<img width="593" alt="screen shot 2017-10-05 at 21 46 40" src="https://user-images.githubusercontent.com/8135252/31249198-b4ccdb58-aa16-11e7-9d01-b83d1f256409.png">

**Comment by jukben** [comment]
This is the last version 😂. Maybe this one is the cleanes...

<img width="593" alt="screen shot 2017-10-05 at 21 50 43" src="https://user-images.githubusercontent.com/8135252/31249363-4ea2c652-aa17-11e7-812e-cf785354e644.png">

**Comment by xilopaint** [comment]
The latest is much better and cleaner than the former ones.

**Comment by xilopaint** [comment]
Have you set any autoupdate feature for your workflow?

**Comment by jukben** [comment]
Hi @xilopaint, there should be a message about newer version provided by [Alfy](https://github.com/sindresorhus/alfy). 

`npm i -g  alfred-emoji`

But feel free to run for getting the most recent version. I hope you like it.
