### ISSUE TITLE
Installation error - path/file can't be found

### ISSUE THREAD

**Issue by codycodes** [jukben/alfred-emoji#3]
Thanks for your quick response to the previous issue! So I've tried a few times/ways to install (reinstalling, removing, ensuring npm was updated), but they all gave me this error:

```
npm ERR! path /usr/local/lib/node_modules/alfred-emoji/node_modules/match-sorter/node_modules/diacritic
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/alfred-emoji/node_modules/match-sorter/node_modules/diacritic' -> '/usr/local/lib/node_modules/alfred-emoji/node_modules/match-sorter/node_modules/.diacritic.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I also ensured that my node.js was up-to-date by installing nvm. When doing so I got a tree of packages that showed what might be useful info for alfred-emoji:

![89a09de7-ff63-406b-802b-e9e50433d5c1](https://user-images.githubusercontent.com/8005593/34653521-9f1817ee-f3a1-11e7-87d5-226d94a74526.png)

**Comment by jukben** [comment]
Could you share exactly commands what have you run? 

I've tried to reinstall the package and everything for me went well. 
```
~ npm -g install alfred-emoji

> alfred-emoji@0.0.4 postinstall /usr/local/lib/node_modules/alfred-emoji
> alfy-init

+ alfred-emoji@0.0.4
added 142 packages in 9.303s
~ npm -v
5.6.0
~ node -v
v9.3.0
```

**Comment by jukben** [comment]
Closeed for inactivity. If you still facing the problem, feel free to open a new issue.
