### ISSUE TITLE
Update alfy to 0.8.0 in package.json

### ISSUE THREAD

**Issue by timgcarlson** [jukben/alfred-emoji#5]
This will fix this issue: https://github.com/SamVerschueren/alfred-link/pull/20

It occurs when a user tries installing your workflow from npm as their very first workflow after installing Alfred 3. It is because a `/workflows` does not exist until you create a workflow in Alfred.

**Comment by jukben** [comment]
Oh, thanks for that, I'll do it. 👍

**Comment by jukben** [comment]
Fixed in https://github.com/jukben/alfred-emoji/commit/c5c1d89b674a2a9c3693d5db97ee660de04c6462 🚀 Deployed as 0.2.1
